# Generated by Django 5.0.7 on 2024-08-17 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='read',
            new_name='seen',
        ),
    ]
