# Generated by Django 5.0.7 on 2024-08-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfts',
            name='image',
            field=models.ImageField(default='nfts/Salin1.png', upload_to='nfts/'),
        ),
    ]
