# Generated by Django 5.0.7 on 2024-08-12 22:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfts', '0002_nfts_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nfts',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_nfts', to=settings.AUTH_USER_MODEL),
        ),
    ]
