# Generated by Django 5.0.7 on 2024-09-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfts', '0003_nfts_liked_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nfts',
            options={'ordering': ['-created_at'], 'permissions': [('can_change_nft', 'Can change NFT')], 'verbose_name': 'NFT', 'verbose_name_plural': 'NFTs'},
        ),
    ]
